CREATE TABLE  `_DATABASE_NAME_`.`TestTable` (
  `testID` int(10) NOT NULL auto_increment,
  PRIMARY KEY  USING BTREE (`testID`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE `_DATABASE_NAME_`.`TestTable`;

